Pass global options to provision and join calls
samba-in-kubernetes/sambacc pull request #45
Opened 2022-06-03 15:20 UTC by phlogistonjohn

Support taking global options defined in the configuration and passing them onto the samba-tools commands that will generate smb.conf.

2022-06-03 17:58 UTC, phlogistonjohn commented
Unit tests are fine, but testing it practically I don't see the option making it into smb.conf, even though I've confirmed were passing the --option=foo=bar CLI arguments.  I'm going to leave this as a draft until I do some more practical tests and understand what samba-tool expects the options to be.

2022-06-22 14:24 UTC, phlogistonjohn commented
Getting the exact combination of CLI and smb.conf to work is proving tricky. I haven't given up on this tho.

2022-11-22 17:14 UTC, obnoxxx requested changes
please rebase on current master and resolve conflicts.

2022-11-28 15:51 UTC, phlogistonjohn commented
I can, unfortunately the code does not function as intended. I haven't had time to follow up on this as I think we'll need to better understand / discuss the behavior of samba-tool with regards to default options.  JFYI

2023-01-06 15:12 UTC, closed without merging

2023-01-06 15:13 UTC, phlogistonjohn commented
Closed because this approach just won't work and it's been over 6 months outstanding. There's still an open issue to work on this which is *not* being closed.