tox.ini: avoid one tox warning when running py3-mypy
samba-in-kubernetes/sambacc pull request #54
Opened 2022-11-16 20:19 UTC by phlogistonjohn

Rework how the tox.ini file is organized in order to remove a `command found but not installed in testenv` when running tox. We currently need at least one test run to be executed with system site packages enabled, but we don't need it that way for mypy.

2022-11-21 07:09 UTC, synarete approved these changes
LGTM

2022-11-22 10:40 UTC, obnoxxx requested changes
just a small irrelevant typo ...

2022-11-22 10:40 UTC, obnoxxx commented on tox.ini
> +# sitepackages option. However when it is eanbled and you already have a tool
```suggestion
# sitepackages option. However when it is enabled and you already have a tool
```

2022-11-22 15:55 UTC, phlogistonjohn commented on tox.ini
> +# sitepackages option. However when it is eanbled and you already have a tool
typo fixed. thanks!

2022-11-22 17:29 UTC, obnoxxx approved these changes
Thanks for fixing the typo ! I don't know enough about tox etc, to provide a knowledgeable review, but it looks clean enough and seems to work ... LGTM

2022-11-23 17:42 UTC, merged