docs: add first full document describing JSON config
samba-in-kubernetes/sambacc pull request #56
Opened 2022-12-05 19:43 UTC by phlogistonjohn

The sambacc configuration format has mostly been something only those brave enough to read code (and some examples) could understand. This initial document describing the sambacc JSON configuration format aims to rectify that situation.

NOTE: this isn't full documentation for sambacc, but it's a good first step as the JSON configuration drives so much of the behavior of sambacc. This is part of a wider effort to document the samba-containers and sambacc since much of the focus so far has been documenting only the samba-operator.

2022-12-08 15:41 UTC, obnoxxx commented on docs/configuration.md
> +instances.
```suggestion
instances.
```
```suggestion
instance.
```

2022-12-08 15:52 UTC, obnoxxx requested changes
updated suggestion/ request ...

2022-12-08 18:52 UTC, phlogistonjohn commented on docs/configuration.md
> +instances.
fixed

2022-12-08 18:52 UTC, phlogistonjohn commented on docs/configuration.md
> +The `users` section helps define local users for a non domain member server
fixed

2022-12-08 18:53 UTC, phlogistonjohn commented on docs/configuration.md
> +instances.
fixed

2022-12-08 18:53 UTC, phlogistonjohn commented on docs/configuration.md
> +The `groups` section helps define local groups for a non domain member server
fixed

2022-12-09 17:51 UTC, obnoxxx commented on docs/configuration.md
> +The `groups` section helps define local groups for a non domain member server
thanks!

2022-12-09 17:51 UTC, obnoxxx commented on docs/configuration.md
> +instances.
Thanks!

2022-12-09 17:52 UTC, obnoxxx commented on docs/configuration.md
> +The `users` section helps define local users for a non domain member server
> fixed

Thanks!

2022-12-09 17:59 UTC, obnoxxx approved these changes
Thanks for the update, @phlogistonjohn  - just one addiotional thought inline. but this lgmt, now!

2022-12-09 17:59 UTC, obnoxxx commented on docs/configuration.md
> +* `uid` - Optional integer. Specify the exact Unix UID the user should have.
wondering if it would be helpful to state that the underlying unix uer will be created  with trhis ID. (at least I think it will) - just a thought.

2022-12-09 17:59 UTC, merged